name: flutter_map_supercluster_example
description: Example for Flutter Map Supercluster

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_map: ^4.0.0
  flutter_map_supercluster:
    path: ../
  flutter_map_animations: ^0.3.0
  flutter_map_marker_popup: ^5.1.0
  latlong2: ^0.8.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: AccurateMapIcon
      fonts:
        - asset: fonts/AccurateMapIcon.ttf
